spring:
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/kemao_2?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
     username: kemao_2
     password: 1234
   jpa:  
  #自动创表
     generate-ddl: true
  #自动生成SQL打印
     show-sql: true
   
   redis: 
     host: 120.79.158.183 
     port: 6379
     database: 13
    
 #  没有web所以不要端口
#server.port: 8040

  
